# Generated by Django 4.2.15 on 2024-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_commentreport_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
